from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

from .schema import RobotConfig, load_robot_config


class ConfigGenerationError(RuntimeError):
    pass


def _cpp_float(value: float) -> str:
    rendered = format(float(value), ".8g")
    if "." not in rendered and "e" not in rendered.lower():
        rendered += ".0"
    return f"{rendered}F"


def _float_array(name: str, values: np.ndarray | tuple[float, ...]) -> str:
    entries = ", ".join(_cpp_float(value) for value in values)
    return f"constexpr std::array<float, {len(values)}> {name} = {{{entries}}};"


def _int_array(name: str, values: np.ndarray) -> str:
    entries = ", ".join(str(int(value)) for value in values)
    return f"constexpr std::array<int8_t, {len(values)}> {name} = {{{entries}}};"


def _hash_array(config_hash: bytes) -> str:
    rows = []
    for offset in range(0, len(config_hash), 8):
        row = ", ".join(f"0x{value:02x}" for value in config_hash[offset : offset + 8])
        rows.append(f"    {row},")
    return "\n".join(rows)


def render_firmware_header(
    config: RobotConfig,
) -> str:
    if (
        config.external_target_execution_ready
        or config.external_target_acceptance_ready
    ) and not config.hardware_parameters_verified:
        raise ConfigGenerationError(
            "external target execution cannot be enabled while hardware parameters are unverified"
        )

    lines = [
        "#ifndef DUMMY_ROBOT_CONFIG_GENERATED_HPP",
        "#define DUMMY_ROBOT_CONFIG_GENERATED_HPP",
        "",
        "// Generated by dummy-host-generate-firmware-config. Do not edit by hand.",
        "// The SHA-256 covers canonical robot-safety fields; CameraRig is independent.",
        "// Joint limits/initial pose use URDF coordinates. kJointZeroOffsetRad is",
        "// the legacy firmware angle at URDF zero; see joint_space_mapping.hpp.",
        "",
        "#include <array>",
        "#include <cstdint>",
        "",
        "namespace dummy::generated_config",
        "{",
        f'constexpr char kRobotId[] = "{config.robot_id}";',
        f'constexpr char kRobotCalibrationId[] = "{config.robot_calibration_id}";',
        f"constexpr uint32_t kConfigVersion = {config.config_version}U;",
        "constexpr bool kHardwareParametersVerified = "
        + ("true;" if config.hardware_parameters_verified else "false;"),
        "constexpr bool kExternalTargetExecutionReady = "
        + ("true;" if config.external_target_execution_ready else "false;"),
        "constexpr bool kExternalTargetAcceptanceReady = "
        + ("true;" if config.external_target_acceptance_ready else "false;"),
        "constexpr std::array<uint8_t, 32> kConfigSha256 = {",
        _hash_array(config.config_hash_bytes),
        "};",
        "",
        _float_array("kJointZeroOffsetRad", config.joint_zero_offset_rad),
        _int_array("kJointSign", config.joint_sign),
        _float_array("kJointReduction", config.joint_reduction),
        _float_array("kInitialPoseRad", config.initial_pose_rad),
        _float_array("kJointMinRad", config.joint_limit_min_rad),
        _float_array("kJointMaxRad", config.joint_limit_max_rad),
        _float_array("kMaxVelocityRadS", config.joint_velocity_limit_rad_s),
        _float_array("kMaxAccelerationRadS2", config.joint_acceleration_limit_rad_s2),
        _float_array("kGripperRange", config.gripper_range),
        f"constexpr bool kGripperStateFeedback = {str(config.gripper_state_feedback).lower()};",
        f"constexpr float kGripperVelocityLimitPerS = {_cpp_float(config.gripper_velocity_limit_per_s)};",
        f"constexpr float kGripperAccelerationLimitPerS2 = {_cpp_float(config.gripper_acceleration_limit_per_s2)};",
        _float_array("kJointFollowingErrorLimitRad", config.joint_following_error_limit_rad),
        f"constexpr float kGripperFollowingErrorLimit = {_cpp_float(config.gripper_following_error_limit)};",
        f"constexpr uint32_t kFollowingErrorHoldMs = {config.following_error_hold_ms}U;",
        f"constexpr uint32_t kFeedbackHoldMs = {config.feedback_hold_ms}U;",
        f"constexpr uint32_t kFeedbackFaultMs = {config.feedback_fault_ms}U;",
        f"constexpr uint32_t kTemperatureMaxAgeMs = {config.temperature_max_age_ms}U;",
        f"constexpr float kTemperatureFaultC = {_cpp_float(config.temperature_fault_c)};",
        f"constexpr uint32_t kTemperatureFaultMs = {config.temperature_fault_ms}U;",
        f"constexpr uint32_t kHostControlRateHz = {config.control_rate_hz}U;",
        f"constexpr uint32_t kFirmwareLoopHz = {config.firmware_loop_hz}U;",
        f"constexpr uint32_t kCanSchedulerWatchdogHz = {config.can_scheduler_watchdog_hz}U;",
        f"constexpr uint32_t kCanTargetHzPerNode = {config.can_target_hz_per_node}U;",
        f"constexpr uint32_t kCanPositionHzPerNode = {config.can_position_hz_per_node}U;",
        f"constexpr uint32_t kCanTemperatureHzPerNode = {config.can_temperature_hz_per_node}U;",
        f"constexpr uint32_t kCoherentMaxSkewUs = {config.coherent_max_skew_ms * 1000}U;",
        f"constexpr uint32_t kCanNodeQuietUs = {config.can_node_quiet_us}U;",
        f"constexpr uint32_t kCanResponseTimeoutUs = {config.can_response_timeout_us}U;",
        f"constexpr uint32_t kCanTxAbortTimeoutUs = {config.can_tx_abort_timeout_us}U;",
        f"constexpr uint32_t kCanTargetFanoutTimeoutUs = {config.can_target_fanout_timeout_us}U;",
        f"constexpr uint32_t kMaxStateAgeMs = {config.max_state_age_ms}U;",
        f"constexpr uint16_t kTargetTtlMs = {config.target_ttl_ms}U;",
        f"constexpr uint32_t kLeaseTimeoutMs = {config.lease_timeout_ms}U;",
        f"constexpr float kMaxTargetOvershootRad = {_cpp_float(config.max_target_overshoot_rad)};",
        "",
        "static_assert(kFirmwareLoopHz == 200U, \"firmware loop contract changed\");",
        "static_assert(!(kExternalTargetExecutionReady && kExternalTargetAcceptanceReady), \"production and acceptance gates must be mutually exclusive\");",
        "static_assert(kCanSchedulerWatchdogHz >= 100U && kCanSchedulerWatchdogHz <= 5000U, \"CAN scheduler watchdog rate is outside the reviewed range\");",
        "static_assert(kCanResponseTimeoutUs <= kCanNodeQuietUs, \"CAN response timeout must fit inside the node quiet interval\");",
        "static_assert(kCanTargetFanoutTimeoutUs >= kCanTxAbortTimeoutUs, \"CAN fanout deadline must cover one transport abort deadline\");",
        "static_assert(kTargetTtlMs > 0U, \"target TTL must be positive\");",
        "static_assert(kLeaseTimeoutMs >= kTargetTtlMs, \"lease must not expire before target TTL\");",
        "static_assert(kFeedbackFaultMs > kFeedbackHoldMs, \"feedback FAULT must persist beyond HOLD\");",
        "",
        "} // namespace dummy::generated_config",
        "",
        "#endif // DUMMY_ROBOT_CONFIG_GENERATED_HPP",
        "",
    ]
    return "\n".join(lines)


def generate_firmware_header(
    config_path: str | Path,
    output_path: str | Path,
    *,
    check: bool = False,
) -> bool:
    config = load_robot_config(config_path)
    rendered = render_firmware_header(config)
    output = Path(output_path)
    if check:
        try:
            existing = output.read_text(encoding="utf-8")
        except OSError as exc:
            raise ConfigGenerationError(f"cannot read generated header {output}: {exc}") from exc
        if existing != rendered:
            raise ConfigGenerationError(
                f"generated header {output} is stale; regenerate it from {config_path}"
            )
        return False
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(rendered, encoding="utf-8", newline="\n")
    return True


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate the STM32 robot configuration header from robot_config.yaml"
    )
    parser.add_argument("--config", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    generate_firmware_header(
        args.config,
        args.output,
        check=args.check,
    )


if __name__ == "__main__":
    main()
