#ifndef DUMMY_ROBOT_CONFIG_GENERATED_HPP
#define DUMMY_ROBOT_CONFIG_GENERATED_HPP

// Generated by dummy-host-generate-firmware-config. Do not edit by hand.
// The SHA-256 covers canonical robot-safety fields; CameraRig is independent.
// Joint limits/initial pose use URDF coordinates. kJointZeroOffsetRad is
// the legacy firmware angle at URDF zero; see joint_space_mapping.hpp.

#include <array>
#include <cstdint>

namespace dummy::generated_config
{
constexpr char kRobotId[] = "dummy_v2_001";
constexpr char kRobotCalibrationId[] = "dummy_v2_001-arm-gripper-20260821-v2";
constexpr uint32_t kConfigVersion = 7U;
constexpr bool kHardwareParametersVerified = true;
constexpr bool kExternalTargetExecutionReady = true;
constexpr std::array<uint8_t, 32> kConfigSha256 = {
    0x66, 0x52, 0x5f, 0xc5, 0xf1, 0x34, 0x7f, 0x60,
    0x42, 0xef, 0xe8, 0x4a, 0x87, 0xe2, 0xd5, 0xb5,
    0x2b, 0x9a, 0x9f, 0xf0, 0xf1, 0x94, 0xf9, 0xc7,
    0x82, 0xba, 0x21, 0x0e, 0xd4, 0x36, 0xcf, 0x64,
};

constexpr std::array<float, 6> kJointZeroOffsetRad = {0.0F, -1.2740901F, 3.141593F, 0.0F, 0.0F, 0.0F};
constexpr std::array<int8_t, 6> kJointSign = {1, 1, 1, -1, 1, -1};
constexpr std::array<float, 6> kJointReduction = {50.0F, 50.0F, 50.0F, 50.0F, 50.0F, 50.0F};
constexpr std::array<float, 6> kInitialPoseRad = {0.0F, 0.052359879F, 0.0F, 0.0F, 0.0F, 0.0F};
constexpr std::array<float, 6> kJointMinRad = {-2.9670596F, 0.052359879F, -2.6179938F, -3.1415927F, -1.5707964F, -3.4906585F};
constexpr std::array<float, 6> kJointMaxRad = {2.9670596F, 3.0194197F, 0.0F, 3.1415927F, 1.5707964F, 6.2831855F};
constexpr std::array<float, 6> kMaxVelocityRadS = {0.34999999F, 0.34999999F, 0.34999999F, 0.5F, 0.5F, 0.69999999F};
constexpr std::array<float, 6> kMaxAccelerationRadS2 = {0.69999999F, 0.69999999F, 0.69999999F, 1.0F, 1.0F, 1.4F};
constexpr std::array<float, 2> kGripperRange = {0.0F, 1.0F};
constexpr bool kGripperStateFeedback = true;
constexpr float kGripperVelocityLimitPerS = 0.2F;
constexpr float kGripperAccelerationLimitPerS2 = 0.8F;
constexpr std::array<float, 6> kJointFollowingErrorLimitRad = {0.12F, 0.12F, 0.12F, 0.15000001F, 0.15000001F, 0.18000001F};
constexpr float kGripperFollowingErrorLimit = 0.15F;
constexpr uint32_t kFollowingErrorHoldMs = 250U;
constexpr uint32_t kFeedbackHoldMs = 100U;
constexpr uint32_t kFeedbackFaultMs = 500U;
constexpr uint32_t kTemperatureMaxAgeMs = 2500U;
constexpr float kTemperatureFaultC = 75.0F;
constexpr uint32_t kTemperatureFaultMs = 1000U;
constexpr uint32_t kHostControlRateHz = 20U;
constexpr uint32_t kFirmwareLoopHz = 200U;
constexpr uint32_t kCanSchedulerWatchdogHz = 1000U;
constexpr uint32_t kCanTargetHzPerNode = 50U;
constexpr uint32_t kCanPositionHzPerNode = 40U;
constexpr uint32_t kCanTemperatureHzPerNode = 1U;
constexpr uint32_t kCoherentMaxSkewUs = 30000U;
constexpr uint32_t kMaxStateAgeMs = 200U;
constexpr uint16_t kTargetTtlMs = 200U;
constexpr uint32_t kLeaseTimeoutMs = 500U;
constexpr float kMaxTargetOvershootRad = 0.1F;

static_assert(kFirmwareLoopHz == 200U, "firmware loop contract changed");
static_assert(kCanSchedulerWatchdogHz >= 100U && kCanSchedulerWatchdogHz <= 5000U, "CAN scheduler watchdog rate is outside the reviewed range");
static_assert(kTargetTtlMs > 0U, "target TTL must be positive");
static_assert(kLeaseTimeoutMs >= kTargetTtlMs, "lease must not expire before target TTL");
static_assert(kFeedbackFaultMs > kFeedbackHoldMs, "feedback FAULT must persist beyond HOLD");

} // namespace dummy::generated_config

#endif // DUMMY_ROBOT_CONFIG_GENERATED_HPP
