#ifndef DUMMY_ROBOT_CONFIG_GENERATED_HPP
#define DUMMY_ROBOT_CONFIG_GENERATED_HPP

// Generated by dummy-host-generate-firmware-config. Do not edit by hand.
// The SHA-256 covers canonical robot-safety fields; CameraRig is independent.
// Joint limits/initial pose use URDF coordinates. kJointZeroOffsetRad is
// the legacy firmware angle at URDF zero; see joint_space_mapping.hpp.

#include <array>
#include <cstdint>

namespace dummy::generated_config
{
constexpr char kRobotId[] = "dummy_v2_001";
constexpr char kRobotCalibrationId[] = "dummy_v2_001-arm-gripper-20260821-v2";
constexpr uint32_t kConfigVersion = 4U;
constexpr bool kHardwareParametersVerified = true;
constexpr bool kExternalTargetExecutionReady = true;
constexpr std::array<uint8_t, 32> kConfigSha256 = {
    0x3a, 0xc2, 0x0a, 0x54, 0x76, 0xb6, 0x6f, 0x10,
    0x49, 0x29, 0x32, 0x19, 0xd8, 0x3f, 0x78, 0x7e,
    0x2a, 0xe5, 0x93, 0x16, 0xd3, 0x40, 0x96, 0x27,
    0x01, 0xa8, 0x03, 0x7b, 0x5d, 0xa5, 0xef, 0x1f,
};

constexpr std::array<float, 6> kJointZeroOffsetRad = {0.0F, -1.2740901F, 3.141593F, 0.0F, 0.0F, 0.0F};
constexpr std::array<int8_t, 6> kJointSign = {1, 1, 1, -1, 1, -1};
constexpr std::array<float, 6> kJointReduction = {50.0F, 50.0F, 50.0F, 50.0F, 50.0F, 50.0F};
constexpr std::array<float, 6> kInitialPoseRad = {0.0F, 0.052359879F, 0.0F, 0.0F, 0.0F, 0.0F};
constexpr std::array<float, 6> kJointMinRad = {-2.9670596F, 0.052359879F, -2.6179938F, -3.1415927F, -1.5707964F, -3.4906585F};
constexpr std::array<float, 6> kJointMaxRad = {2.9670596F, 3.0194197F, 0.0F, 3.1415927F, 1.5707964F, 6.2831855F};
constexpr std::array<float, 6> kMaxVelocityRadS = {0.34999999F, 0.34999999F, 0.34999999F, 0.5F, 0.5F, 0.69999999F};
constexpr std::array<float, 6> kMaxAccelerationRadS2 = {0.69999999F, 0.69999999F, 0.69999999F, 1.0F, 1.0F, 1.4F};
constexpr std::array<float, 2> kGripperRange = {0.0F, 1.0F};
constexpr bool kGripperStateFeedback = true;
constexpr uint32_t kHostControlRateHz = 20U;
constexpr uint32_t kFirmwareLoopHz = 200U;
constexpr uint32_t kMaxStateAgeMs = 200U;
constexpr uint16_t kTargetTtlMs = 100U;
constexpr uint32_t kLeaseTimeoutMs = 500U;
constexpr float kMaxTargetOvershootRad = 0.1F;

static_assert(kFirmwareLoopHz == 200U, "firmware loop contract changed");
static_assert(kTargetTtlMs > 0U, "target TTL must be positive");
static_assert(kLeaseTimeoutMs >= kTargetTtlMs, "lease must not expire before target TTL");

} // namespace dummy::generated_config

#endif // DUMMY_ROBOT_CONFIG_GENERATED_HPP
