#ifndef DUMMY_ROBOT_CONFIG_GENERATED_HPP
#define DUMMY_ROBOT_CONFIG_GENERATED_HPP

// Generated by dummy-host-generate-firmware-config. Do not edit by hand.
// The SHA-256 covers canonical robot-safety fields; CameraRig is independent.
// Joint limits/initial pose use URDF coordinates. kJointZeroOffsetRad is
// the legacy firmware angle at URDF zero; see joint_space_mapping.hpp.

#include <array>
#include <cstdint>

namespace dummy::generated_config
{
constexpr char kRobotId[] = "dummy_v2_001";
constexpr char kRobotCalibrationId[] = "dummy_v2_001-arm-gripper-20260821-v2";
constexpr uint32_t kConfigVersion = 6U;
constexpr bool kHardwareParametersVerified = true;
constexpr bool kExternalTargetExecutionReady = true;
constexpr std::array<uint8_t, 32> kConfigSha256 = {
    0x4b, 0xa2, 0x77, 0x32, 0xf4, 0x24, 0x27, 0x02,
    0x81, 0x70, 0xe8, 0xfb, 0xd9, 0x56, 0x90, 0xa2,
    0xb1, 0xfe, 0xc6, 0x0e, 0x70, 0x6f, 0xd4, 0x15,
    0xf4, 0xd1, 0x1f, 0x29, 0xa3, 0x30, 0xf2, 0x58,
};

constexpr std::array<float, 6> kJointZeroOffsetRad = {0.0F, -1.2740901F, 3.141593F, 0.0F, 0.0F, 0.0F};
constexpr std::array<int8_t, 6> kJointSign = {1, 1, 1, -1, 1, -1};
constexpr std::array<float, 6> kJointReduction = {50.0F, 50.0F, 50.0F, 50.0F, 50.0F, 50.0F};
constexpr std::array<float, 6> kInitialPoseRad = {0.0F, 0.052359879F, 0.0F, 0.0F, 0.0F, 0.0F};
constexpr std::array<float, 6> kJointMinRad = {-2.9670596F, 0.052359879F, -2.6179938F, -3.1415927F, -1.5707964F, -3.4906585F};
constexpr std::array<float, 6> kJointMaxRad = {2.9670596F, 3.0194197F, 0.0F, 3.1415927F, 1.5707964F, 6.2831855F};
constexpr std::array<float, 6> kMaxVelocityRadS = {0.34999999F, 0.34999999F, 0.34999999F, 0.5F, 0.5F, 0.69999999F};
constexpr std::array<float, 6> kMaxAccelerationRadS2 = {0.69999999F, 0.69999999F, 0.69999999F, 1.0F, 1.0F, 1.4F};
constexpr std::array<float, 2> kGripperRange = {0.0F, 1.0F};
constexpr bool kGripperStateFeedback = true;
constexpr float kGripperVelocityLimitPerS = 0.2F;
constexpr float kGripperAccelerationLimitPerS2 = 0.8F;
constexpr std::array<float, 6> kJointFollowingErrorLimitRad = {0.12F, 0.12F, 0.12F, 0.15000001F, 0.15000001F, 0.18000001F};
constexpr float kGripperFollowingErrorLimit = 0.15F;
constexpr uint32_t kFollowingErrorHoldMs = 250U;
constexpr uint32_t kFeedbackHoldMs = 100U;
constexpr uint32_t kFeedbackFaultMs = 500U;
constexpr uint32_t kTemperatureMaxAgeMs = 2500U;
constexpr float kTemperatureFaultC = 75.0F;
constexpr uint32_t kTemperatureFaultMs = 1000U;
constexpr uint32_t kHostControlRateHz = 20U;
constexpr uint32_t kFirmwareLoopHz = 200U;
constexpr uint32_t kFeedbackPollHz = 700U;
constexpr uint32_t kMaxStateAgeMs = 200U;
constexpr uint16_t kTargetTtlMs = 100U;
constexpr uint32_t kLeaseTimeoutMs = 500U;
constexpr float kMaxTargetOvershootRad = 0.1F;

static_assert(kFirmwareLoopHz == 200U, "firmware loop contract changed");
static_assert(kFeedbackPollHz >= 7U && kFeedbackPollHz <= 1000U, "feedback poll rate is outside the reviewed range");
static_assert(kFeedbackPollHz % 7U == 0U, "feedback poll rate must divide evenly across seven nodes");
static_assert(kTargetTtlMs > 0U, "target TTL must be positive");
static_assert(kLeaseTimeoutMs >= kTargetTtlMs, "lease must not expire before target TTL");
static_assert(kFeedbackFaultMs > kFeedbackHoldMs, "feedback FAULT must persist beyond HOLD");

} // namespace dummy::generated_config

#endif // DUMMY_ROBOT_CONFIG_GENERATED_HPP
