from __future__ import annotations

from typing import Protocol, runtime_checkable

import numpy as np

from .models import AppliedAction, ControlMode, RobotHealth, RobotState


@runtime_checkable
class RobotBackend(Protocol):
    @property
    def is_connected(self) -> bool: ...

    def connect(self) -> None: ...
    def disconnect(self) -> None: ...
    def acquire_control(self, mode: str | ControlMode) -> None: ...
    def release_control(self) -> None: ...
    def read_state(self, max_age_ms: int | None = None) -> RobotState: ...

    def apply_absolute_action(
        self,
        action: np.ndarray,
        *,
        source: str = "direct",
        max_velocity_rad_s: np.ndarray | None = None,
    ) -> AppliedAction: ...

    def hold(self) -> None: ...
    def emergency_stop(self) -> None: ...
    def health(self) -> RobotHealth: ...
