#ifndef DUMMY_CAN_TRANSPORT_CONTRACT_H
#define DUMMY_CAN_TRANSPORT_CONTRACT_H

#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

enum
{
    DUMMY_MOTOR_DIAGNOSTICS_FORMAT_V2 = 0xA2,
    DUMMY_MOTOR_DIAGNOSTICS_FORMAT_OFFSET = 4,
    DUMMY_MOTOR_TX_DROP_OFFSET = 5,
    DUMMY_MOTOR_RX_ERROR_OFFSET = 6,
    DUMMY_MOTOR_BUSOFF_OFFSET = 7,
    DUMMY_MOTOR_TIMING_COMMAND = 0x26,
    DUMMY_MOTOR_TIMING_FORMAT_V1 = 0xA9,
    DUMMY_MOTOR_TIMING_PAGE_CAN_SERVICE = 0,
    DUMMY_MOTOR_TIMING_PAGE_CONTROL_JITTER = 1,
    DUMMY_MOTOR_TIMING_PAGE_CONTROL_EXECUTION = 2,
    DUMMY_MOTOR_TIMING_PAGE_COUNTS = 3,
    DUMMY_MOTOR_TIMING_PAGE_COUNT = 4,
    DUMMY_MOTOR_TIMING_FLAG_DWT_ENABLED = 1U << 0,
    DUMMY_MOTOR_TIMING_FLAG_CAN_VALID = 1U << 1,
    DUMMY_MOTOR_TIMING_FLAG_CONTROL_VALID = 1U << 2,
    DUMMY_MOTOR_TIMING_FLAG_NO_MISSED_TICKS = 1U << 3,
};

static inline uint8_t DummyCanSaturatingIncrement8(uint8_t value)
{
    return value == UINT8_MAX ? value : (uint8_t) (value + 1U);
}

#ifdef __cplusplus
}
#endif

#endif
